### ISSUE TITLE
RASP Pi ZERO MK3 Loses access key / connection on Octoprint Plugin

### ISSUE THREAD

**Issue by rhys100** [AstroPrint/OctoPrint-AstroPrint#28]
Hi, I am not sure what variables are at play but I have the following Setup x2 and both have the same issue

RASP PI ZERO integrated into Prusa MK3 running 1.3.6 octoprint firmware and Astroprint Firmware.

Every day I need to goto the astroprint plugin tab and re input my api key and link them again.

I am not sure if the reset button on MK3 or other variables are at play but this is very annoying :)

**Comment by Alfonsopl** [comment]
We use Oauth2  tokens for provide access to AstroPrint data and boxrouter. 

The only reason that  could make you get unlogged from the plugin is when you get your token expired/unauthorized. That happens after 16 days without using the plugin or very rarely when an error occurs in communications. It that happens you should get a warning in your logs with the message: "refresh token expired, AstroPrint user logged out".

If you can not find the message on your log it could be because of the rasp pi zero. As Lina indicates in Octoprint installation: Raspberry Pi Zero W is not recommended since severe performance issues.

Can you find the warning on your logs or try the plugin in a raspberry 2/3?

**Comment by fred2088** [comment]
got the same problem even uninstall the plugin and install again ...
